### ISSUE TITLE
To Python 3.6+

### ISSUE THREAD

**Issue by yogeshhk** [yogeshhk/MiningResume#1]
Check if the script works in Python 3.6+ and if not make necessary changes

**Comment by aniketartani** [comment]
can I work on this, I have developed a lot of software using python even one was HR management i.e. related to your one.

**Comment by yogeshhk** [comment]
Sure. Please.

**Comment by aburton-stack** [comment]
Checkout these libraries:

python-future - The missing compatibility layer between Python 2 and Python 3.

modernize - Modernizes Python code for eventual Python 3 migration.

six - Python 2 and 3 compatibility utilities.

**Comment by yogeshhk** [comment]
It seems to work ok in Python 3.6+ so closing

**Comment by yogeshhk** [comment]
It seems to work ok in Python 3.6+ so closing
