### ISSUE TITLE
Parse resume programmatically using GPT or any other LLM models

### ISSUE THREAD

**Issue by yogeshhk** [yogeshhk/MiningResume#4]
Similar to regex used to mine resume, evaluate/implement the same by developing Prompts based resume parser

**Comment by yogeshhk** [comment]
Keeping this issue for Swaraj, will assign once he joins

**Comment by yogeshhk** [comment]
https://github.com/eyurtsev/kor

**Comment by swarajendait** [comment]
Pull request #11
