### ISSUE TITLE
Building Web UI

### ISSUE THREAD

**Issue by yogeshhk** [yogeshhk/MiningResume#5]
Put flask UI on current python script
Add folder selection button, show results in tabular format

**Comment by sunny-shankar** [comment]
@yogeshhk I would like to work on this.

**Comment by yogeshhk** [comment]
Ok @sunny-shankar , you can work on first 2, we will have the 3rd ie file types done by another person,  looks ok?

**Comment by sunny-shankar** [comment]
Ok. Can you share any template for reference.

**Comment by yogeshhk** [comment]
Nothing specific as such. Simple layout could be.

Text box for path with button to select folder. This is to pick folder having resumes.

A submit button.

A tabular view to show the results.

**Comment by sunny-shankar** [comment]
I have created something. Could you please provide me with feedback?

![image](https://user-images.githubusercontent.com/41531959/235349479-c4ae9691-0a34-4a3e-ae1a-d68d6cd4c732.png)
![image](https://user-images.githubusercontent.com/41531959/235349482-051aa2fe-c6ae-4d6d-9c3b-eb9352f4305d.png)

**Comment by yogeshhk** [comment]
This is looking nice. Thanks.
Wish to suggest some changes. We will be selecting a folder not a single file. Folder will have many resumes.

So even output should be table with say first column as filename and other columns has headings like name, emails,  skills etc. Looks ok?

**Comment by sunny-shankar** [comment]
Please have a look into it
![image](https://user-images.githubusercontent.com/41531959/235354608-b446f4d2-c88f-45af-a10a-e540d62b596c.png)
![image](https://user-images.githubusercontent.com/41531959/235354615-77daa81f-317c-48bb-a8a6-befa3e81e996.png)

**Comment by yogeshhk** [comment]
Looking good @sunny-shankar

**Comment by sunny-shankar** [comment]
added #7

**Comment by yogeshhk** [comment]
Very nice. Thanks a lot for your contribution

**Comment by yogeshhk** [comment]
Would it be ok to move main.py, 'static' and 'template', inside 'src' so that all the sources stay there. Also, possible to update README on How to run @sunny-shankar

**Comment by sunny-shankar** [comment]
Sure, I have made some changes . Please Check #8

**Comment by yogeshhk** [comment]
Thanks @sunny-shankar
